source "https://rubygems.org"
gemspec

gem 'jekyll-admin', group: :jekyll_plugins
gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins

gem "webrick", "~> 1.7"
